### ISSUE TITLE
Pretraining new language

### ISSUE THREAD

**Issue by Wyzix33** [clovaai/donut#143]
Hi, i have around 100k scanned documents, including a metadata.jsonl formated as the one that synthdog generates:
```
{"file_name": "img_1.jpg", "ground_truth": "{\"gt_parse\": {\"text_sequence\": \Text in Romanian language\"}}"}
```
and i want to create a new pretraining model so that i can fine-tune on it.
I've search and i can't understand how to do it... Can you please share the scripts you used to create "naver-clova-ix/donut-base" so i can generate a new pretraining for a new language?
Thanks

**Comment by logan-markewich** [comment]
pre-training is actually the same as fine-tuning. The only difference is that in pre-training you train the model to predict all the text on the document (or, at least up to the max output size)

**Comment by Wyzix33** [comment]
Thank you, 
so naver-clova-ix/donut-base is not for English language only? I was thinking that i must create a pretrained model on my language to be able to fine-tune documents containing that language.
I will try your solution now.

**Comment by logan-markewich** [comment]
Since they use MBart as the decoder, it has support for multiple languages. However, they only provided fine-tuned models on English or Chinese data.

Good luck!

**Comment by Wyzix33** [comment]
It worked. Thanks

**Comment by Wyzix33** [comment]
Hi, 
here are the configs i used to create the dataset for Romanian language and fine-tune donut on them, i've worked with a single GPU 16GB VRAM and it took about one week to complete.
Then i created another donut config, same as the one in the archive and just changed the `pretrained_model_name_or_path: "naver-clova-ix/donut-base"` to `pretrained_model_name_or_path: "result/ro/ro"` (the folder that was created after first training) and i am now able to fine tune on my model using RO language.
Based on yout GPU memory you may need to change `input_size: [1600, 1920]` must be multiple of 320, `warmup_steps` and `max_epochs`
Also use some better paper backgrounds for synthdog...

[configs.zip](https://github.com/clovaai/donut/files/11097970/configs.zip)

PS when i prepared the dataset for my fine tunning i had less than 100 documents to work with, about 10 distinct models and i've used [DocSim](https://github.com/AI4Bharat/DocSim) to generate more
Let me know if you need something else

**Comment by Wyzix33** [comment]
Sure,  if you want full text only, without fine-tunning on certain things you can use this:
```
from donut import DonutModel
from PIL import Image
import torch
model = DonutModel.from_pretrained("result/ro/ro/")
if torch.cuda.is_available():
    model.half()
    device = torch.device("cuda")
    model.to(device)
else:
    model.encoder.to(torch.bfloat16)
model.eval()
image = Image.open("my_image.jpg")
output = model.inference(image=image, prompt="<s_ro>")
print(output)
```
where my_image is a image with romanian text on it, output is something like this
```
{'predictions': [{'text_sequence': 'romanian text on the page'}]}

```
`"ro"` was the name of my dataset and  `"result/ro/ro/"` was the path where the pretraining saved the files.
Here is a simple tutorial i first followed to understand the process, you can use a small dataset first to see the process 
[Donut tutorial](https://towardsdatascience.com/ocr-free-document-understanding-with-donut-1acfbdf099be)
For document specific information extraction you will want to fine-tune this pretraining on more speciffic text like in the tutorial

**Comment by Wyzix33** [comment]
yes, it will, but it's better to give it a name. add `--exp_version "ro"` to the command so you can use the prompt like this `prompt="<s_ro>"` you can use anything instead of `ro`

**Comment by BakingBrains** [comment]
@Wyzix33 did you replace the tokenizer in https://github.com/clovaai/donut/blob/master/donut/model.py#L159 ?

Thank you

**Comment by Wyzix33** [comment]
No, the only thing i've changed was the config, this is the config i've used fot pre-training:
 ```
resume_from_checkpoint_path: null # only used for resume_from_checkpoint option in PL
result_path: "./result"
pretrained_model_name_or_path: "naver-clova-ix/donut-base" # loading a pre-trained model (from moldehub or path)
dataset_name_or_paths: ["dataset/ro"] # loading datasets (from moldehub or path)
sort_json_key: False # cord dataset is preprocessed, and publicly available at https://huggingface.co/datasets/naver-clova-ix/cord-v2
train_batch_sizes: [1]
val_batch_sizes: [1]
input_size: [1600, 1920] # when the input resolution differs from the pre-training setting, some weights will be newly initialized (but the model training would be okay)
max_length: 768
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 3e-5
warmup_steps: 1000 # 800/8*30/10, 10%
num_training_samples_per_epoch: 800
max_epochs: 100
max_steps: -1
num_workers: 8
val_check_interval: 1.0
check_val_every_n_epoch: 3
gradient_clip_val: 1.0
verbose: True
```
also the dataset generated with SynthDOG used this config:
```
quality: [65, 95]
landscape: 0.3
short_size: [1024, 1024]
aspect_ratio: [1, 2]

# background:
#   image:
#     paths: [resources/background]
#     weights: [0]

#   effect:
#     args:
#       # gaussian blur
#       - prob: 0.3
#         args:
#           sigma: [0, 10]

document:
  fullscreen: 0.6
  landscape: 0.5
  short_size: [1024, 1024]
  aspect_ratio: [1, 2]

  paper:
    image:
      paths: [resources/paper]
      weights: [1]
      alpha: [0, 0.2]
      grayscale: 1
      crop: 1

  content:
    margin: [0, 0.2]
    text:
      path: resources/corpus/ro1.txt
    font:
      paths: [resources/font/ro]
      weights: [1]
      bold: 0
    layout:
      text_scale: [0.02, 0.05]
      max_row: 50
      max_col: 7
      fill: [0.7, 1]
      full: 0.1
      align: [left, right, center]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [0.5, 1]
      stack_full: 0.1
    textbox:
      fill: [0.5, 1]
    textbox_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1
    content_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1

  effect:
    args:
      # elastic distortion
      - prob: 0.2
        args:
          alpha: [0, 1]
          sigma: [0, 0.5]
      # gaussian noise
      - prob: 0.3
        args:
          scale: [0, 8]
          per_channel: 0
      # perspective
      - prob: 0.2
        args:
          weights: [750, 50, 50, 25, 25, 25, 25, 50]
          args:
            - percents: [[0.75, 1], [0.75, 1], [0.75, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [0.75, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [1, 1]]

effect:
  args:
    # color
    - prob: 0.2
      args:
        rgb: [[0, 255], [0, 255], [0, 255]]
        alpha: [0, 0.2]
    # shadow
    - prob: 0.5
      args:
        intensity: [0, 160]
        amount: [0, 1]
        smoothing: [0.5, 1]
        bidirectional: 0
    # contrast
    - prob: 0.5
      args:
        alpha: [1, 1.5]
    # brightness
    - prob: 0.5
      args:
        beta: [-48, 0]
    # motion blur
    - prob: 0.3
      args:
        k: [3, 5]
        angle: [0, 360]
    # gaussian blur
    - prob: 0.4
      args:
        sigma: [0, 1.5]

```
