### ISSUE TITLE
How to config synthdog for much more longer text,  like total length about 1024-2048

### ISSUE THREAD

**Issue by CheungZeeCn** [clovaai/donut#249]
How to config synthdog for much more longer text,  like total length about 1024-2048;

**Comment by CheungZeeCn** [comment]
It seems worked:
```
change:
    layout:
      text_scale: [0.03, 0.1]
      max_row: 80
      max_col: 3
      fill: [0.8, 1]
      full: 0.1
      align: [left, right, center]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [0.8, 1]
      stack_full: 0.1
    textbox:
      fill: [0.9, 1]

add:
font:
  size: [16, 48]
```
